type JsonLdProps = {
  schema: Record<string, unknown> | Array<Record<string, unknown>>;
};

/**
 * Renders Schema.org JSON-LD. Undefined fields are dropped by JSON.stringify,
 * so schema builders can leave optional properties undefined.
 */
export default function JsonLd({schema}: JsonLdProps) {
  return (
    <script
      type="application/ld+json"
      // Content is generated by our own schema builders, never user input.
      dangerouslySetInnerHTML={{__html: JSON.stringify(schema)}}
    />
  );
}
